# Site settings
baseurl = "https://tomger.eu/"
languageCode = "en-us"
title = "tomGER's Blog"
theme = "spectre-pixel"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  name = "tomGER"
  altName = ""
  description = "This is the adventure of a man called tomGER."
  bio = ""
  enableRSS = true

  # Author information in posts
  aboutAuthor = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [
    "https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css"
  ]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
	email    = "blog@tomger.eu"
	github   = "https://www.github.com/tumger"
	twitter  = "https://www.twitter.com/_tomGER"

[taxonomies]
  tag = "tags"
